[project]
name = "cognos"
version = "0.1.1"
description = "cognos, part of the cognosis project"
authors = [{name = "MOONLAPSED", email = "MOONLAPSED@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}

[project.optional-dependencies]
dev = [
    "pytest",
    "mypy",
    "pytest-cov",
    "black",
    "flake8",
    "pdm-pep517",
    "pdm-pep517-build-backend",
    "isort",
    "tox",
    "pre-commit",
    "cffi",
    "gcc",
    "cmake",
    "ctags",
    "pytest-benchmark",
    "hypothesis",
    "pdm",
    "mamba",
    "micromamba"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
